import { SplToken } from 'src/interfaces/solana';

export const SPL_TOKENS: SplToken[] = [
  {
    publicKey: 'sinjBMHhAuvywW3o87uXHswuRXb3c7TfqgAdocedtDj',
    coinGeckoId: 'invictus',
    name: 'Staked Invictus',
    symbol: 'IN',
  },
  {
    publicKey: 'inL8PMVd6iiW3RCBJnr5AsrRN6nqr4BTrcNuQWQSkvY',
    coinGeckoId: 'invictus',
    name: 'Invictus',
    symbol: 'IN',
  },
  {
    publicKey: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    coinGeckoId: 'usd-coin',
    name: 'USDC',
    symbol: 'USDC',
  },
  {
    publicKey: 'CWE8jPTUYhdCTZYWPTe1o5DFqfdjzWKc9WKz6rSjQUdG',
    coinGeckoId: 'chainlink',
    name: 'Chainlink',
    symbol: 'LINK',
  },
  {
    publicKey: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
    coinGeckoId: 'raydium',
    name: 'Raydium',
    symbol: 'RAY',
  },
  {
    publicKey: 'SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt',
    coinGeckoId: 'serum',
    name: 'Serum',
    symbol: 'SRM',
  },
  {
    publicKey: 'C98A4nkJXhpVZNAZdHUA95RpTF3T4whtQubL3YobiUX9',
    coinGeckoId: 'coin98',
    name: 'Coin98',
    symbol: 'C98',
  },
  {
    publicKey: 'C98A4nkJXhpVZNAZdHUA95RpTF3T4whtQubL3YobiUX9',
    coinGeckoId: 'coin98',
    name: 'Coin98',
    symbol: 'C98',
  },
  {
    publicKey: 'ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx',
    coinGeckoId: 'star-atlas',
    name: 'Star Atlas',
    symbol: 'ATLAS',
  },
  {
    publicKey: 'MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac',
    coinGeckoId: 'mango-markets',
    name: 'Mango',
    symbol: 'MNGO',
  },
  {
    publicKey: 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
    coinGeckoId: 'bonfida',
    name: 'Bonfida',
    symbol: 'FIDA',
  },
  {
    publicKey: 'xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW',
    coinGeckoId: 'solanium',
    name: 'Solanium',
    symbol: 'SLIM',
  },
  {
    publicKey: 'AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
    coinGeckoId: 'aurory',
    name: 'Aurory',
    symbol: 'AURY',
  },
  {
    publicKey: 'CsZ5LZkDS7h9TDKjrbL7VAwQZ9nsRu8vJLhRYfmGaN8K',
    coinGeckoId: 'aleph',
    name: 'Aleph.im',
    symbol: 'ALEPH',
  },
  {
    publicKey: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
    coinGeckoId: 'aleph',
    name: 'Star Atlas DAO',
    symbol: 'POLIS',
  },
  {
    publicKey: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    coinGeckoId: 'samoyedcoin',
    name: 'Samoyedcoin',
    symbol: 'SAMO',
  },
  {
    publicKey: 'DFL1zNkaGPWm1BqAVqRjCZvHmwTFrEaJtbzJWgseoNJh',
    coinGeckoId: 'defi-land',
    name: 'DeFi Land',
    symbol: 'DFL',
  },
  {
    publicKey: 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
    coinGeckoId: 'msol',
    name: 'Marinade Staked SOL',
    symbol: 'mSOL',
  },
  {
    publicKey: '9S4t2NEAiJVMvPdRYKVrfJpBafPBLtvbvyS3DecojQHw',
    coinGeckoId: 'frontier-token',
    name: 'Frontier',
    symbol: 'FRONT',
  },
  {
    publicKey: 'z3dn17yLaGMKffVogeFHQ9zWVcXgqgf3PQnDsNs2g6M',
    coinGeckoId: 'oxygen',
    name: 'Oxygen',
    symbol: 'OXY',
  },
  {
    publicKey: '3bRTivrVsitbmCTGtqwp7hxXPsybkjn4XLNtPsHqa3zR',
    coinGeckoId: 'only1',
    name: 'Only1',
    symbol: 'LIKE',
  },
  {
    publicKey: 'PRSMNsEPqhGVCH1TtWiJqPjJyh2cKrLostPZTNy1o5x',
    coinGeckoId: 'prism',
    name: 'Prism',
    symbol: 'PRISM',
  },
  {
    publicKey: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    coinGeckoId: 'tether',
    name: 'Tether',
    symbol: 'USTD',
  },
  {
    publicKey: '5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm',
    coinGeckoId: 'socean-staked-sol',
    name: 'Socean Staked Sol',
    symbol: 'SCNSOL',
  },
  {
    publicKey: 'kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6',
    coinGeckoId: 'kin',
    name: 'Kin',
    symbol: 'KIN',
  },
  {
    publicKey: 'ChVzxWRmrTeSgwd3Ui3UumcN8KX7VK3WaD4KGeSKpypj',
    coinGeckoId: 'sushi',
    name: 'Sushi',
    symbol: 'SUSHI',
  },
  {
    publicKey: 'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
    coinGeckoId: 'orca',
    name: 'Orca',
    symbol: 'ORCA',
  },
  {
    publicKey: 'JET6zMJWkCN9tpRT2v2jfAmm5VnQFDpUBCyaKojmGtz',
    coinGeckoId: 'jet',
    name: 'Jet',
    symbol: 'JET',
  },
  {
    publicKey: 'StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT',
    coinGeckoId: 'step-finance',
    name: 'Step Finance',
    symbol: 'STEP',
  },
  {
    publicKey: 'TuLipcqtGVXP9XR62wM8WWCm6a9vhLs7T1uoWBk6FDs',
    coinGeckoId: 'solfarm',
    name: 'Tulip Protocol',
    symbol: 'TULIP',
  },
  {
    publicKey: 'GsNzxJfFn6zQdJGeYsupJWzUAm57Ba7335mfhWvFiE9Z',
    coinGeckoId: 'dexlab',
    name: 'Dexlab',
    symbol: 'DXL',
  },
];
