name: update-solana
on:
  schedule:
    - cron: '0 16 * * *' # 9am daily (PST)
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://us-central1-whooshwallet.cloudfunctions.net/api/updateSolanaAssets' \
