name: update-gemini
on:
  schedule:
    - cron: '0 18 * * *' # 11am daily (PST)
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://us-central1-whooshwallet.cloudfunctions.net/api/updateGeminiAssets' \
